import type { Metadata } from "next";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { barlow } from "@/app/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add Google Material Icons link here */}
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body className={`${barlow} antialiased`}>
        <Nav />
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
