import type { Metadata } from "next";
import {barlow} from "@/app/ui/fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow} ${barlow} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
